ci(debug): Add check job for Docker username secret
Add a job to check for empty Docker username secret.

Signed-off-by: Jack Edwards <je@jacksec.engineer>

diff --git a/.github/workflows/security.yml b/.github/workflows/security.yml
--- a/.github/workflows/security.yml
+++ b/.github/workflows/security.yml
@@ -13,6 +13,17 @@ env:
   IMAGE_NAME: linkshort
 
 jobs:
+  check:
+    name: check creds
+    runs-on: ubuntu-latest
+    run: |
+      if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
+        echo "Error: DOCKER_USERNAME is empty!"
+        exit 1
+      else
+        echo "DOCKER_USERNAME is populated."
+      fi
+
   semgrep:
     name: Analyze (semgrep)
     runs-on: ubuntu-24.04
